const sampleRecipeTitles = 
['Tarragon Chicken',
  'Seared Steak',
  'Brown Butter Orecchiette',
  'Summer Squash and Ricotta Tartines',
  'Four-Cheese Pizza',
  'Creamy Chicken Fettuccine',
  'Duck Sliders',
  'Moroccan Meatloaf',
  'Brie Mac and Cheese',
  'Chicken Caesar Panzanella',
  'Grilled Caprese Burgers',
  'Mushroom Cavatelli',
  'Prosciutto and Pea Farfalle',
  'Crispy Chicken Sandwiches',
  'Indian Butter Chicken',
  'Herbed Sausage Hash',
  'Lemon-Herb Salmon',
  'Miso-Citrus Chicken Thighs',
  'Coconut-Lime Rice Pudding',
  'Seared Steak',
  'Cashew Chicken',
  'Salmon with Salsa Verde',
  'Chicken, Radish, and Pea Salad',
  'Braised Pork, Apricots, and Currants',
  'Beef and Eggplant Stir-Fry',
  'Fish Tacos',
  'Seared Steak',
  'Crunchy Pork Milanese'];